export const cantadas = [
    "Você é o Google? Porque tem tudo o que estou procurando.",
    "Aposto um beijo que você me dá um fora.",
    "Se beleza fosse tempo, você seria a eternidade.",
    "Você não é um dicionário, mas é a definição de beleza.",
    "Se você fosse uma fruta, você seria um morango, porque é a fruta mais bonita.",
    "Seu pai deve ser um ladrão, porque ele roubou as estrelas do céu e colocou nos seus olhos.",
    "Você é um feitiço, porque sempre está na ponta da minha língua.",
    "Você tem um mapa? Porque me perdi no seu sorriso.",
    "Eu não sou fotógrafo, mas posso nos imaginar juntos.",
    "Se você fosse uma flor, eu escolheria você.",
    "Você acredita em amor à primeira vista, ou devo passar por aqui de novo?",
    "Você é tão doce que poderia causar diabetes.",
    "Você tem um nome ou posso te chamar de minha?",
    "Se você fosse um número, seria o número um.",
    "Você é o que acontece quando sonhos se tornam realidade.",
    "Você não é uma câmera, mas cada vez que olho para você, sorrio.",
    "Eu não sou mágico, mas posso fazer todos os seus desejos se tornarem realidade.",
    "Você é como uma rosa, quanto mais eu te cheiro, mais eu gosto de você.",
    "Se beleza fosse tempo, você seria a eternidade.",
    "Se você fosse uma estrela, seria a mais brilhante do céu.",
    "Você tem um mapa? Porque me perdi em seus olhos.",
    "Você não está cansada? Porque você tem corrido na minha mente o dia todo.",
    "Se você fosse um oceano, eu nadaria até o fim para te encontrar.",
    "Eu não sou um fotógrafo, mas posso facilmente nos ver juntos.",
    "Você é o que eu tenho procurado a minha vida toda.",
    "Você é como um diamante precioso: raro e incrivelmente lindo.",
    "Eu não sou um astrônomo, mas posso ver nossos futuros alinhados.",
    "Você não é a Mona Lisa, mas você é definitivamente o melhor trabalho de arte que já vi.",
    "Eu não sou um cartão de crédito, mas adoraria ser o motivo do seu sorriso.",
    "Se você fosse um livro, eu não conseguiria parar de ler.",
    "Sua mão parece pesada. Deixe-me segurá-la para você.",
    "Eu não sou um DJ, mas posso tocar a música do seu coração.",
    "Você é a resposta para todas as minhas preces.",
    "Você não é a gravidade, mas parece estar me puxando para você.",
    "Você é um ladrão? Porque você roubou meu coração.",
    "Eu não sou um palhaço, mas definitivamente faria você sorrir.",
    "Se você fosse uma cor, seria a mais bonita do arco-íris.",
    "Você tem um nome, ou eu posso te chamar de minha?",
    "Se eu fosse um gato, gastaria todas as minhas vidas com você.",
    "Eu não sou um banco, mas você pode depositar toda a sua confiança em mim.",
    "Eu não sou um mágico, mas posso fazer você desaparecer com um beijo.",
    "Se você fosse uma estrela, eu faria um desejo a cada noite.",
    "Você é a razão pela qual as auroras acontecem.",
    "Você não é uma lanterna, mas você ilumina o meu mundo.",
    "Seu pai deve ser um relojoeiro, porque ele fez um trabalho perfeito no tempo que você tem.",
    "Se você fosse uma música, seria a melhor melodia que já ouvi.",
    "Eu não sou um astronauta, mas posso te levar para as estrelas.",
    "Se você fosse um ovo, você seria um ovo incrível.",
    "Se beleza fosse um crime, você estaria cumprindo prisão perpétua.",
    "Eu não sou um dicionário, mas definitivamente tenho uma definição para você.",
    "Você é como um arco-íris: bonito, colorido e faz o meu dia ficar melhor.",
    "Você é o que acontece quando o amor e a beleza se encontram.",
    "Se você fosse um ímã, eu seria de metal, porque estou atraído por você.",
    "Você não é uma rosa, mas ainda é a flor mais bonita do jardim.",
    "Você é a melhor coisa desde o pão fatiado.",
    "Eu não sou um fotógrafo, mas posso nos ver juntos.",
    "Você é o motivo pelo qual os unicórnios ainda existem.",
    "Se você fosse uma joia, seria uma esmeralda rara e preciosa.",
    "Eu não sou um cirurgião, mas posso consertar seu coração.",
    "Você é como um tesouro: difícil de encontrar, mas vale a pena a busca.",
    "Você é a razão pela qual as flores desabrocham.",
    "Eu não sou um escritor, mas você é a minha história de amor.",
    "Se eu pudesse reorganizar o alfabeto, colocaria U e I juntos.",
    "Você é como um diamante bruto: deslumbrante e inexplorado.",
    "Eu não sou um super-herói, mas vou ser o seu herói.",
    "Você é como um raio de sol em um dia chuvoso.",
    "Você é a resposta para todas as minhas perguntas.",
    "Eu não sou um pintor, mas você é a minha obra-prima.",
    "Você é a única que está faltando na minha vida.",
    "Você é como uma estrela cadente: rara e incrivelmente bonita.",
    "Eu não sou um jardineiro, mas definitivamente quero plantar um beijo em você.",
    "Você é o que acontece quando a perfeição encontra a beleza.",
    "Você é a razão pela qual os arco-íris têm cores.",
    "Eu não sou um chef, mas definitivamente faria algo especial para você.",
    "Você é como uma poesia: linda e cheia de significado.",
    "Você é a música que toca no meu coração.",
    "Eu não sou um matemático, mas definitivamente faria você somar na minha vida.",
    "Você é como um sonho tornado realidade.",
    "Você é a melhor parte do meu dia.",
    "Eu não sou um ladrão, mas roubaria um beijo seu a qualquer momento.",
    "Você é como uma obra de arte: única e fascinante.",
    "Você é a razão pela qual o sol brilha.",
    "Eu não sou um astrônomo, mas adoraria explorar o seu universo.",
    "Você é como um farol em minha vida escura.",
    "Você é a resposta para todas as minhas orações.",
    "Eu não sou um poeta, mas você me inspira a escrever versos de amor.",
    "Você é como um presente que eu não sabia que desejava até te conhecer.",
    "Você é a estrela que brilha mais forte no meu céu noturno.",
    "Eu não sou um cientista, mas você é a minha descoberta mais incrível.",
    "Você é como um raio de sol em um dia nublado.",
    "Você é a razão pela qual o meu coração bate mais rápido.",
    "Eu não sou um jogador, mas definitivamente apostaria tudo em você.",
    "Você é como uma pérola rara no oceano da vida.",
    "Você é a melodia que faz o meu coração dançar.",
    "Eu não sou um bombeiro, mas faria de tudo para apagar o fogo do seu coração.",
    "Você é como um diamante precioso: raro e inestimável.",
    "Você é a razão pela qual o mundo é um lugar melhor.",
    "Eu não sou um mágico, mas faria todos os seus desejos se tornarem realidade.",
    "Você é como uma estrela cadente: única e deslumbrante.",
    "Você é a luz que ilumina o meu caminho.",
    "Eu não sou um arqueólogo, mas adoraria desenterrar todos os seus segredos.",
    "Você é como um arco-íris em um dia chuvoso: um vislumbre de esperança.",
    "Você é a razão pela qual os pássaros cantam de alegria.",
    "Eu não sou um marinheiro, mas você é a minha âncora.",
    "Você é como um diamante bruto: deslumbrante e cheio de potencial.",
    "Se você fosse um botão, eu apertaria você o dia todo.",
    "Você é como o sol: quente, brilhante e essencial para minha vida.",
    "Se beleza fosse tempo, você seria a eternidade em pessoa.",
    "Você não é um erro, você é uma exceção perfeita.",
    "Sua voz deve ser um instrumento, porque cada palavra é uma melodia.",
    "Você é tão doce que acho que ganhei uma cárie só de olhar para você.",
    "Eu não sou um fotógrafo, mas posso nos imaginar juntos em uma foto perfeita.",
    "Seu sorriso ilumina até a noite mais escura.",
    "Você é como uma estrela cadente: rara e incrivelmente bela.",
    "Você é como uma obra de arte que eu nunca vou cansar de admirar.",
    "Você é o que acontece quando o amor e a beleza se encontram.",
    "Eu não sou um astrônomo, mas nossos corações estão em perfeita órbita.",
    "Você é a razão pela qual os arco-íris têm cores.",
    "Se você fosse uma flor, você seria a mais rara e preciosa do jardim.",
    "Você é como um diamante bruto: deslumbrante e cheio de potencial.",
    "Eu não sou um poeta, mas você me inspira a escrever versos de amor.",
    "Você é a melodia que faz o meu coração dançar.",
    "Eu não sou um bombeiro, mas faria de tudo para apagar o fogo do seu coração.",
    "Você é como uma pérola rara no oceano da vida.",
    "Você é a luz que ilumina o meu caminho.",
    "Eu não sou um arqueólogo, mas adoraria desenterrar todos os seus segredos.",
    "Você é como um arco-íris em um dia chuvoso: um vislumbre de esperança.",
    "Você é a razão pela qual os pássaros cantam de alegria.",
    "Eu não sou um marinheiro, mas você é a minha âncora.",
    "Você é como um diamante brilhante: raro e inestimável.",
    "Você é a razão pela qual o mundo é um lugar melhor.",
    "Eu não sou um mágico, mas faria todos os seus desejos se tornarem realidade.",
    "Você é como uma estrela cadente: única e deslumbrante.",
    "Você é a luz que ilumina o meu caminho.",
    "Eu não sou um arqueólogo, mas adoraria desenterrar todos os seus segredos.",
    "Você é como um arco-íris em um dia chuvoso: um vislumbre de esperança.",
    "Você é a razão pela qual os pássaros cantam de alegria.",
    "Eu não sou um marinheiro, mas você é a minha âncora.",
    "Você é como um diamante brilhante: raro e inestimável.",
    "Você é a razão pela qual o mundo é um lugar melhor.",
    "Eu não sou um mágico, mas faria todos os seus desejos se tornarem realidade.",
    "Você é como uma estrela cadente: única e deslumbrante.",
    "Se você fosse uma música, seria a minha canção favorita.",
    "Você é como uma estrela no céu, brilhando mais do que todas as outras.",
    "Eu não sou um chef, mas faria algo especial para você todos os dias.",
    "Se você fosse uma pedra preciosa, você seria a joia mais rara e valiosa.",
    "Você é como um sonho bom que eu nunca quero acordar.",
    "Eu não sou um poeta, mas você é a minha inspiração constante.",
    "Você é como uma borboleta: delicada, graciosa e bela.",
    "Você é a razão pela qual meu coração bate mais rápido.",
    "Eu não sou um jogador, mas definitivamente apostaria tudo em você.",
    "Você é como uma pérola no oceano: rara e magnífica.",
    "Sua beleza é como uma obra-prima que nunca envelhece.",
    "Eu não sou um mágico, mas podemos fazer nossos desejos se tornarem realidade.",
    "Seu sorriso é como um raio de sol em um dia nublado.",
    "Você é como uma estrela brilhante no meu céu noturno.",
    "Eu não sou um jardineiro, mas faria você florescer de felicidade.",
    "Você é a razão pela qual a lua fica com ciúmes à noite.",
    "Eu não sou um piloto, mas voaria ao redor do mundo por você.",
    "Você é como um diamante perfeitamente lapidado: raro e deslumbrante.",
    "Se eu pudesse reorganizar o alfabeto, colocaria U e I juntos.",
    "Você é como um diamante na areia: um tesouro escondido.",
    "Eu não sou um poeta, mas você é a minha poesia favorita.",
    "Você é como um farol que me guia nas noites escuras.",
    "Você é a razão pela qual as estrelas brilham à noite.",
    "Eu não sou um mergulhador, mas mergulharia fundo em seus olhos.",
    "Você é como um doce que derrete no coração.",
    "Você é a razão pela qual o amor está no ar.",
    "Eu não sou um cientista, mas nossa química é indescritível.",
    "Você é como um raio de sol em um dia chuvoso.",
    "Você é a razão pela qual meu mundo gira.",
    "Eu não sou um carteiro, mas adoraria entregar meu coração a você.",
    "Você é como uma rosa: linda, elegante e cheia de graça.",
    "Você é a razão pela qual os pássaros cantam de alegria.",
    "Eu não sou um mágico, mas faria todos os seus desejos se tornarem realidade.",
    "Você é como uma estrela cadente: única e deslumbrante.",
    "Você é a luz que ilumina o meu caminho.",
    "Eu não sou um arqueólogo, mas adoraria desenterrar todos os seus segredos.",
    "Você é como um arco-íris em um dia chuvoso: um vislumbre de esperança.",
    "Você é a razão pela qual os pássaros cantam de alegria.",
    "Eu não sou um marinheiro, mas você é a minha âncora.",
    "Você é como um diamante brilhante: raro e inestimável.",
    "Você é a razão pela qual o mundo é um lugar melhor.",
    "Eu não sou um mágico, mas faria todos os seus desejos se tornarem realidade.",
    "Você é como uma estrela cadente: única e deslumbrante.",
    "Se você fosse uma música, seria a minha canção favorita.",
    "Você é como uma estrela no céu, brilhando mais do que todas as outras.",
    "Eu não sou um chef, mas faria algo especial para você todos os dias.",
    "Se você fosse uma pedra preciosa, você seria a joia mais rara e valiosa.",
    "Você é como um sonho bom que eu nunca quero acordar.",
    "Eu não sou um poeta, mas você é a minha inspiração constante.",
    "Você é como uma borboleta: delicada, graciosa e bela.",
    "Você é a razão pela qual meu coração bate mais rápido.",
    "Eu não sou um jogador, mas definitivamente apostaria tudo em você.",
    "Você é como uma pérola no oceano: rara e magnífica.",
    "Sua beleza é como uma obra-prima que nunca envelhece.",
    "Eu não sou um mágico, mas podemos fazer nossos desejos se tornarem realidade.",
    "Seu sorriso é como um raio de sol em um dia nublado.",
    "Você é como uma estrela brilhante no meu céu noturno.",
    "Eu não sou um jardineiro, mas faria você florescer de felicidade.",
    "Você é a razão pela qual a lua fica com ciúmes à noite.",
    "Eu não sou um piloto, mas voaria ao redor do mundo por você.",
    "Você é como um diamante perfeitamente lapidado: raro e deslumbrante.",
    "Se eu pudesse reorganizar o alfabeto, colocaria U e I juntos.",
    "Você é como um diamante na areia: um tesouro escondido.",
    "Eu não sou um poeta, mas você é a minha poesia favorita.",
    "Você é como um farol que me guia nas noites escuras.",
    "Você é a razão pela qual as estrelas brilham à noite.",
    "Eu não sou um mergulhador, mas mergulharia fundo em seus olhos.",
    "Você é como um doce que derrete no coração.",
    "Você é a razão pela qual o amor está no ar.",
    "Eu não sou um cientista, mas nossa química é indescritível.",
    "Você é como um raio de sol em um dia chuvoso.",
    "Você é a razão pela qual meu mundo gira.",
    "Eu não sou um carteiro, mas adoraria entregar meu coração a você.",
    "Você é como uma rosa: linda, elegante e cheia de graça."
];
